version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
      ci-tooling:
        patterns:
          - "golangci/*"
          - "golang/*"
          - "github/codeql-action"
          - "codecov/*"
      release-tooling:
        patterns:
          - "goreleaser/*"
          - "anchore/*"
          - "sigstore/*"
