# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: echoip

before:
  hooks:
    - go mod tidy

builds:
  - id: echoip
    main: .
    binary: echoip
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - id: archive
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.spdx.json"

signs:
  - id: cosign
    cmd: cosign
    artifacts: checksum
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - ${artifact}
    output: true

release:
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Tag }}"
