name: CI Go

on: push

jobs:
  check-dep-change:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
    - name: Check outdated dependencies
      run: go mod tidy -diff

  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
         go-version: '1.24.5'
    - name: Check format according to gofmt
      run: test -z $(gofmt -l .)

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
         go-version: '1.24.5'
    - name: Test
      run: go test -v ./...

